application: g02me
version: 2
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /tests
  static_dir: tests

- url: /images
  static_dir: images
    
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  mime_type: image/vnd.microsoft.icon 

- url: /.*
  script: main.py

