application: g02me
version: 3
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /tests
  static_dir: tests

- url: /images
  static_dir: images
    
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  mime_type: image/vnd.microsoft.icon

# For Google Webmaster Tools domain validation  
- url: /google9eab28331a1ab405.html
  static_files: static/google9eab28331a1ab405.html
  upload: static/google9eab28331a1ab405.html
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# Python Shell for administrative tasks
# See http://code.google.com/p/google-app-engine-samples/source/browse/trunk/shell
- url: /shell.*
  script: shell.py
  login: admin
  
- url: /static
  static_dir: static
  expiration: 1d

# Django handler
- url: /.*
  script: main.py
